services:
  db:
    image: postgres:latest
    container_name: event_platform_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: event_db
    ports:
      - "5433:5432" # Using 5433 to avoid potential local conflicts
    volumes:
      - db_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: event_platform_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
